name: CI

on:
  push:

jobs:
  check:
    name: Execute test, check style, lint...
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements_dev.txt
          pip install -r requirements.txt
      - name: Test application with tox
        run: |
          tox
